apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: user-container
        image: nginx:latest
